name: Build React 17

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:cli
      - run: cd examples/react-17 && npm i && npm run build
